updated script-update and prepare scripts

diff --git a/install/tools/prepare b/install/tools/prepare
--- a/install/tools/prepare
+++ b/install/tools/prepare
@@ -13,33 +13,33 @@ DRY=0
 while [ $# -gt 0 ]
 do
   case "$1" in
-  
+
     "-h"|"--help")
       echo "Usage: $0 [--check-only] [-h|--help] [-n] [-l <dir>|<file.bat>] [<winlang>|ALL|WHOLE]"
       echo
-      echo "download or check all required files for installation scripts"
+      echo "Download or check all required files for installation scripts"
       echo "by parsing *.bat scripts."
       echo
-      echo "  -h, --help           (this) online help."
-      echo "  -n                   dry mode: do not download or check, just echo url to work on."  
-      echo "  --check-only         do not perform download, just check URL validity"
-      echo "  -l <dir>|<file.bat>  work with folder <dir> or file <file.bat> ; use folder scripts/ if nothing specified."
-      echo "  <winlang>            language to download/check; use 'ENU' if not provided."          
-      echo "  WHOLE                work with all languages: mainly usefull for --check-only operations."
+      echo "  -h, --help           Show this help message."
+      echo "  -n                   Dry mode: just echo URL, don't download or check."
+      echo "  --check-only         Only check URL validity, don't download."
+      echo "  -l <dir>|<file.bat>  Target script folder or file. Defaults to 'scripts/'."
+      echo "  <winlang>            Language code. Defaults to 'ENU'."
+      echo "  WHOLE                Process all languages (mainly for --check-only)."
       exit 0
       ;;
-  
+
     "--check-only")
       shift
       SPIDER="--spider"
       ;;
-  
+
     "-l")
       shift
       SCRIPTLOC="$1"
       shift
       ;;
-  
+
     "-n")
       shift
       DRY=1
@@ -55,57 +55,47 @@ done
 # checks
 if [ ! -f "$SCRIPTLOC" ] && [ ! -d "$SCRIPTLOC" ]
 then
-  echo "ERROR: '$SCRIPTLOC' is neither a folder or a file."
+  echo "ERROR: '$SCRIPTLOC' is neither a folder nor a file."
   exit 1
 fi
 
-# regular expression to find url and file location based on lang
-REGEXFORLANG="URL\|($WINLANG|ALL)"
-if [ "$WINLANG" = "WHOLE" ]; then REGEXFORLANG="URL\|"; fi
+REGEXFORLANG="URL\\|($WINLANG|ALL)"
+if [ "$WINLANG" = "WHOLE" ]; then REGEXFORLANG="URL\\|"; fi
 
 # list of files to work on
-WFILES="$SCRIPTLOC"   # default: file
+WFILES="$SCRIPTLOC"
 if [ -d "$SCRIPTLOC" ]
 then
-  WFILES=$( egrep -lri "$REGEXFORLANG" $SCRIPTLOC/*.bat )
+  WFILES=$(egrep -lri "$REGEXFORLANG" $SCRIPTLOC/*.bat)
 fi
 
 wgetnberr=0
 for cmdfile in $WFILES; do
 
   echo
-  echo Processing $cmdfile
+  echo "Processing $cmdfile"
 
-  # Look for URL|LANG in scripts/ + second arg
-  for needed in `egrep -hri "$REGEXFORLANG" $cmdfile | tr ' ' '~'`; do
-      url=`echo -ne "$needed" | cut -d\| -f3 | tr '~' ' ' | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//'`
-      file=`echo -ne "$needed" | cut -d\| -f4 | tr '~' ' '  | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//;s/([^\/]*\/*)$/lc($1)/eg'`
-      path=`echo -ne "$file" | perl -pe 's#(.*/).*#$1#'`
+  for needed in $(egrep -hri "$REGEXFORLANG" $cmdfile | tr ' ' '~'); do
+      url=$(echo -ne "$needed" | cut -d\| -f3 | tr '~' ' ' | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//')
+      file=$(echo -ne "$needed" | cut -d\| -f4 | tr '~' ' ' | perl -pe 's/[\r\n]//g;s/^ *//;s/ *$//;s#([^/]*/?)$#lc($1)#eg')
+      path=$(echo -ne "$file" | perl -pe 's#(.*/).*#$1#')
 
-      if [ $DRY -eq 1 ]; then echo "dry: url=$url"; echo "dry: file=$file" ; continue; fi
+      if [ $DRY -eq 1 ]; then echo "dry: url=$url"; echo "dry: file=$file"; continue; fi
 
       if [ ! "$SPIDER" == "" ]; then
-        wget $SPIDER --passive-ftp "$url" ;
-        if [ $? -ne 0 ]; then wgetnberr=$(( $wgetnberr + 1 )); fi
+        wget $SPIDER "$url"
+        if [ $? -ne 0 ]; then wgetnberr=$(( wgetnberr + 1 )); fi
         continue
       fi
-      # Make sure path is available
+
       mkdir -p "$path"
-      # Download file if it doesn't exist
-      if [ ! -f "$file" ] ; then
-        if [ ${url: -7} == "torrent" ]; then
-          wget $WGET_OPS --passive-ftp -O "$file.$$.torrent" "$url" ;
-          if ctorrent -e 0 -s "$file.$$.tmp" "$file.$$.torrent" ; then
-              mv "$file.$$.tmp" "$file"
-          fi
-        else
-          if wget $SPIDER $WGET_OPS --passive-ftp -O "$file.$$.tmp" "$url" ; then
+      if [ ! -f "$file" ]; then
+          if wget $SPIDER $WGET_OPS -O "$file.$$.tmp" "$url"; then
               mv "$file.$$.tmp" "$file"
           else
               rm -f "$file.$$.tmp"
-              wgetnberr=$(( $wgetnberr + 1 ))
+              wgetnberr=$(( wgetnberr + 1 ))
           fi
-        fi
       else
           touch "$file"
       fi
@@ -114,4 +104,4 @@ for cmdfile in $WFILES; do
 done
 
 echo
-echo "nb of wget errors: $wgetnberr."
+echo "Number of wget errors: $wgetnberr."
diff --git a/install/tools/script-update b/install/tools/script-update
--- a/install/tools/script-update
+++ b/install/tools/script-update
@@ -1,72 +1,51 @@
 #!/bin/bash
 
-#
 # This script updates your script files from the official
-# unattended repository.
-#
-# This scripts crawles through your script directory, and
-# tries to update every found file from the repository. You can
-# define exceptions in this script.
-#
-# Warning #1: this scripts overwrites YOUR changes to official
-# script files without any warning! Please double-check that
-# none of your own-written scripts accidentially have the same
-# name than any of the official scripts.
-#
-# Warning #2: it does not add scripts in the repository that are
-# not found in your script directory. You have to download
-# new scripts once manually.
-#
-# Warning #3: you might want to call it as cron job, but
-# please be not surprised by broken scripts.
-# This happens from time to time.
-#
+# GitHub repository using sparse-checkout (only 'install/scripts').
 
-#  you can write exceptions like this:
-# exceptions=( "win2ksp4-updates.bat" "win2ksp4-symbols.bat" )
-exceptions=( )
+# Define the GitHub repository URL (replace with the actual one)
+GIT_URL="https://github.com/thegamershollow/Unattended"
 
-# HTTP-Link to the cvs-repository
-SVNLINK="https://unattended.svn.sourceforge.net/svnroot/unattended/trunk/install/scripts"
+# Define the subdirectory to checkout
+SPARSE_PATH="install/scripts"
 
-# paths to needed programs
-WGET=$(which wget)
-FIND=$(which find)
-GREP=$(which grep)
-SORT=$(which sort)
-SVN=$(which svn)
+# Define the destination directory
+DEST_DIR="scripts"
 
-# Change to the scripts directory so paths are correct
-cd "$(dirname "$0")"/../scripts
+# Move to the script's parent directory
+cd "$(dirname "$0")"/..
 
-
-if [ ! -f $SVN ]
-then
-   echo \****** INSTALL SVN ON YOUR SYSTEM *************\*
+# Check if Git is installed
+if ! command -v git >/dev/null 2>&1; then
+    echo "Error: Git is not installed or not in PATH."
+    exit 1
 fi
 
-#If there is SVN information when use svn as it has better support
-if [ -d .svn ]
-then
-    $SVN up
-    exit 0
-else
-    echo \****** MISING SVN INFO *************\*
-    echo \*            RUN:
-    echo \*   mv scripts scripts.old
-    echo \*   svn co $SVNLINK scripts 
-    echo \****** MISING SVN INFO *************\*
+# If the destination directory exists and is a Git repo, pull updates
+if [ -d "$DEST_DIR/.git" ]; then
+    echo "Updating existing Git checkout in '$DEST_DIR'..."
+    cd "$DEST_DIR"
+    git pull
+# If the destination exists but isn't a Git repo, back it up and clone fresh
+elif [ -d "$DEST_DIR" ]; then
+    echo "Directory '$DEST_DIR' exists but is not a Git repository."
+    BACKUP_DIR="${DEST_DIR}_backup_$(date +%Y%m%d%H%M%S)"
+    echo "Backing up existing directory to '$BACKUP_DIR'..."
+    mv "$DEST_DIR" "$BACKUP_DIR"
 fi
 
+# If DEST_DIR doesn't exist or was just backed up, perform sparse checkout
+if [ ! -d "$DEST_DIR" ]; then
+    echo "Performing sparse checkout of '$SPARSE_PATH'..."
+    mkdir "$DEST_DIR"
+    cd "$DEST_DIR"
+    git init
+    git remote add origin "$GIT_URL"
+    git config core.sparseCheckout true
+    echo "$SPARSE_PATH/" > .git/info/sparse-checkout
+    git pull origin main  # Replace 'main' with 'master' if needed
+    mv "$SPARSE_PATH"/* .
+    rm -rf "$SPARSE_PATH"
+fi
 
-# crawl through the script-dir
-for file in $($FIND . -type f -name "*.bat" | $GREP -v .svn | $SORT)
-do
-    if [[ "${exceptions[@]%%${file##./}}" != "${exceptions[@]}" ]]; then continue; fi
-    if $WGET $1 --output-document "$file.$$.tmp" $SVNLINK/$file
-    then
-        mv "$file.$$.tmp" "$file"
-    else
-        rm -f "$file.$$.tmp"
-    fi
-done
+echo "Update complete. Scripts are located in the '$DEST_DIR' directory."
